{
 "title": "Kubernetes cluster overview",
 "description": "This dashboard can help troubleshooting issue in Kubernetes cluster at cluster, node and namespace level.",
 "tags": [
  "kubernetes",
  "k8s",
  "namespace"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(up,cluster)" },
   {
    "name": "node",
    "query": "label_values(kube_node_created{cluster=\"$cluster\"},node)"
   },
   {
    "name": "namespace",
    "query": "query_result(kube_namespace_labels{cluster=\"$cluster\"})"
   },
   {
    "name": "container",
    "query": "kube_pod_container_info{cluster=\"$cluster\",namespace=\"$namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall cluster $cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$cluster cluster node status",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "targets": [
    {
     "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$cluster cluster node status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " count(count by (namespace)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " count(count by (pod)(container_spec_memory_reservation_limit_bytes{cluster=\"$cluster\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=\"$cluster\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{cluster=\"$cluster\",reason!=\"Completed\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting/Terminated pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{cluster=\"$cluster\",reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
    },
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason{cluster=\"$cluster\"} !=0 )",
     "legendFormat": "WAITING::{{reason}}::{{namespace}}"
    },
    {}
   ]
  }
 ]
}