{
 "title": "HAProxy Instance Summary (Designed for PMM)",
 "description": "This dashboard displays the detailed HAProxy information of sections and backend servers.",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "service_name",
    "label": "HAProxy Instance",
    "query": "label_values(haproxy_up, service_name)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_bytes_in_total{service_name=\"$service_name\"}, backend)"
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_bytes_in_total{service_name=~\"$service_name\"}, frontend)"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values({__name__=~\"haproxy_server_bytes_in_total|haproxy_frontend_bytes_in_total\"}, server)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   },
   {
    "name": "node_name",
    "label": "Nodename",
    "query": "label_values(haproxy_server_bytes_in_total{service_name=~\"$service_name\"}, node_name)"
   },
   {
    "name": "tcp_backend",
    "label": "TCPBackend",
    "query": "query_result(haproxy_backend_weight{service_name=\"$service_name\"}>0)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "HAProxy Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg by (service_name) (haproxy_up{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Frontend Sections Statuses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 3 },
   "targets": [
    {
     "expr": "count by (service_name,frontend) (haproxy_frontend_limit_sessions{service_name=~\"$service_name\",frontend=~\"$frontend\"})",
     "legendFormat": "{{frontend}}"
    }
   ]
  },
  {
   "title": "Active Servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by () (haproxy_backend_current_server{backend=~\"$backend\"})"
    }
   ]
  },
  {
   "title": "Beckend Sections Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "avg by (service_name,backend) (haproxy_backend_up{service_name=~\"$service_name\",backend=~\"$backend\"})",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Backend (-) / Frontend (+)" }
   ],
   "targets": [
    {
     "expr": "sum by () (haproxy_backend_current_sessions{backend=~\"$backend\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by () (haproxy_frontend_current_sessions{frontend=~\"$frontend\"})",
     "legendFormat": "Fronend"
    }
   ]
  },
  {
   "title": "Servers in $tcp_backend Section",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "repeat": "tcp_backend",
   "targets": [
    {
     "expr": "avg by (service_name,backend,server) (haproxy_server_up{service_name=~\"$service_name\",backend=~\"$tcp_backend\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "HTTP Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Responses by Code",
     "type": "graph",
     "description": "Total of HTTP responses.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,code) (sum by (code) (rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]) or rate(haproxy_backend_http_responses_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_http_responses_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m])))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "HTTP Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "HTTP Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by (service_name,frontend) (rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Connect Time",
     "type": "graph",
     "description": "Avg. HTTP connect time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (max_over_time(haproxy_backend_http_connect_time_average_seconds{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_http_connect_time_average_seconds{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "description": "Avg. HTTP response time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (max_over_time(haproxy_backend_http_response_time_average_seconds{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_http_response_time_average_seconds{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Queue Time",
     "type": "graph",
     "description": "Avg. HTTP queue time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (max_over_time(haproxy_backend_http_queue_time_average_seconds{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_http_queue_time_average_seconds{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "HTTP Total Time",
     "type": "graph",
     "description": "Avg. HTTP total time for last 1024 successful connections.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (max_over_time(haproxy_backend_http_total_time_average_seconds{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_http_total_time_average_seconds{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Data that Bypassed the HTTP Compressor",
     "type": "graph",
     "description": "Number of bytes that bypassed the HTTP compressor",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_compressor_bytes_bypassed_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_compressor_bytes_bypassed_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      },
      {
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_compressor_bytes_bypassed_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_compressor_bytes_bypassed_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "HTTP Response Bytes Fed to the Compressor",
     "type": "graph",
     "description": "Number of HTTP response bytes fed to the compressor",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_compressor_bytes_in_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_compressor_bytes_in_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      },
      {
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_compressor_bytes_in_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_compressor_bytes_in_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "HTTP Response Bytes Emitted by the Compressor",
     "type": "graph",
     "description": "Number of HTTP response bytes emitted by the compressor",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_compressor_bytes_out_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_compressor_bytes_out_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      },
      {
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_compressor_bytes_out_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_compressor_bytes_out_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Compressed HTTP Responses",
     "type": "graph",
     "description": "Number of HTTP responses that were compressed.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by (service_name,backend) (rate(haproxy_backend_http_responses_compressed_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_http_responses_compressed_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend Incoming Data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Frontend Outgoing Data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Backend Incoming Data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_bytes_in_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Backend Outgoing Data",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_bytes_out_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Incoming Data by Servers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_bytes_in_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_bytes_in_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Outgoing Data by Servers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_bytes_out_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_bytes_out_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Section",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "graph",
     "description": "Total number of sessions.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_sessions_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_sessions_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Limit on New Sessions per Second",
     "type": "table",
     "description": "Configured limit on new sessions per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (haproxy_frontend_limit_session_rate{service_name=~\"$service_name\", frontend=~\"$frontend\"})",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Max Observed Number of Sessions per Second",
     "type": "table",
     "description": "Maximum observed number of sessions per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (haproxy_frontend_max_session_rate{service_name=~\"$service_name\", frontend=~\"$frontend\"})",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Sessions Limit",
     "type": "table",
     "description": "Configured session limit.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (haproxy_frontend_limit_sessions{service_name=~\"$service_name\", frontend=~\"$frontend\"})",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Max Number of Active Sessions",
     "type": "table",
     "description": "Maximum observed number of active sessions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (haproxy_frontend_max_sessions{service_name=~\"$service_name\", frontend=~\"$frontend\"})",
       "legendFormat": "{{ frontend }}"
      }
     ]
    },
    {
     "title": "Error Requests",
     "type": "graph",
     "description": "Total of request errors.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Denied Requests",
     "type": "graph",
     "description": "Total of requests denied for security.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,frontend) (rate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{frontend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Section",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "graph",
     "description": "Total number of sessions.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_sessions_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_sessions_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Sessions Rate",
     "type": "graph",
     "description": "Current number of sessions per second over last elapsed second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (max_over_time(haproxy_backend_current_session_rate{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_current_session_rate{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "graph",
     "description": "Current number of active sessions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (max_over_time(haproxy_backend_current_sessions{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_current_sessions{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Connection Errors",
     "type": "graph",
     "description": "Total of connection errors.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_connection_errors_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_backend_connection_errors_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Queued Requests",
     "type": "graph",
     "description": "Current number of queued requests not assigned to any server.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (max_over_time(haproxy_backend_current_queue{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_backend_current_queue{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Redispatch Warnings",
     "type": "graph",
     "description": "Total of redispatch warnings.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or rate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Response Errors",
     "type": "graph",
     "description": "Total of response errors.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_response_errors_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or rate(haproxy_backend_response_errors_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Aborted Data Transfers ",
     "type": "graph",
     "description": "Total number of data transfers aborted by the server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_server_aborts_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or rate(haproxy_backend_server_aborts_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Retry Warnings",
     "type": "graph",
     "description": "Total of retry warnings.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (rate(haproxy_backend_retry_warnings_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or rate(haproxy_backend_retry_warnings_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}}"
      }
     ]
    },
    {
     "title": "Max Observed Number of Sessions per Second",
     "type": "table",
     "description": "Maximum observed number of sessions per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (haproxy_backend_max_session_rate{service_name=~\"$service_name\", backend=~\"$backend\"})",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Max Observed Number of Active Sessions",
     "type": "table",
     "description": "Maximum observed number of active sessions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (haproxy_backend_max_sessions{service_name=~\"$service_name\", backend=~\"$backend\"})",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Sessions Limit",
     "type": "table",
     "description": "Configured session limit.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend) (haproxy_backend_limit_sessions{service_name=~\"$service_name\", backend=~\"$backend\"})",
       "legendFormat": "{{ backend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Servers Weight in $tcp_backend Section",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
     "repeat": "tcp_backend",
     "targets": [
      {
       "expr": "avg by (service_name,backend,server) (haproxy_server_weight{service_name=~\"$service_name\",backend=~\"$tcp_backend\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Servers Weight in $tcp_backend Section",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "avg by (service_name,backend,server) (haproxy_server_weight{service_name=~\"$service_name\",backend=~\"$tcp_backend\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Total Sessions in $tcp_backend Section",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 28 },
     "repeat": "tcp_backend",
     "targets": [
      {
       "expr": "avg by (service_name,backend,server) (haproxy_server_sessions_total{service_name=~\"$service_name\",backend=~\"$tcp_backend\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Total Sessions in $tcp_backend Section",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "avg by (service_name,backend,server) (haproxy_server_sessions_total{service_name=~\"$service_name\",backend=~\"$tcp_backend\"})",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_sessions_total{service_name=~\"$service_name\",backend=~\"$backend\"}[$interval]) or irate(haproxy_server_sessions_total{service_name=~\"$service_name\",backend=~\"$backend\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Health Check Duration",
     "type": "graph",
     "description": "Previously run health check duration, in seconds",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg by (service_name,backend,server) (max_over_time(haproxy_server_check_duration_seconds{service_name=~\"$service_name\",backend=~\"$backend\"}[$interval]) or max_over_time(haproxy_server_check_duration_seconds{service_name=~\"$service_name\",backend=~\"$backend\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Failed Health Checks",
     "type": "graph",
     "description": "Total number of failed health checks.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_check_failures_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_check_failures_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Retry Warnings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_retry_warnings_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_retry_warnings_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Connection Errors",
     "type": "graph",
     "description": "Total of connection errors.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_connection_errors_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_connection_errors_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Response Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_response_errors_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_response_errors_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Queued Requests",
     "type": "graph",
     "description": "Current number of queued requests assigned to this server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (max_over_time(haproxy_server_current_queue{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_server_current_queue{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Aborted Data Transfers",
     "type": "graph",
     "description": "Number of data transfers aborted by the server.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_server_aborts_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_server_aborts_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Sessions Rate",
     "type": "graph",
     "description": "Current number of sessions per second over last elapsed second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (max_over_time(haproxy_server_current_session_rate{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_server_current_session_rate{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "graph",
     "description": "Current number of active sessions.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (max_over_time(haproxy_server_current_sessions{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or max_over_time(haproxy_server_current_sessions{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Downtime",
     "type": "graph",
     "description": "Total downtime in seconds.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_downtime_seconds_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_downtime_seconds_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    },
    {
     "title": "Servers Selections",
     "type": "graph",
     "description": "Number of times a server was selected, either for new sessions, or when re-dispatching.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg by (service_name,backend,server) (rate(haproxy_server_server_selected_total{backend=~\"$backend\",service_name=~\"$service_name\"}[$interval]) or irate(haproxy_server_server_selected_total{backend=~\"$backend\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{backend}} - {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Uptime",
     "type": "singlestat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((node_time_seconds{node_name=~\"$node_name\"} - node_boot_time_seconds{node_name=~\"$node_name\"}) or (time() - node_boot_time_seconds{node_name=~\"$node_name\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "singlestat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 21 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (avg_over_time(node_load1{node_name=~\"$node_name\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$node_name\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "singlestat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 21 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "singlestat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 21 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100)"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "singlestat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 21 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"}+node_memory_SwapTotal_bytes{node_name=~\"$node_name\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "singlestat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 21 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg by (node_name) (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "singlestat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 21 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(node_filesystem_free_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$node_name\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 21 },
     "content": "<h5><b><font color=#e68a00><center><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$node_name\" target=\"_blank\">$crop_host...</a></center></font></b></h5>\n\n\n"
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "graph",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$node_name\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})) or (avg_over_time(node_procs_running{node_name=~\"$node_name\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$node_name\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$proxysql\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$proxysql\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=\"$proxysql\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=\"$proxysql\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_receive_bytes_total{node_name=\"$proxysql\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{node_name=\"$proxysql\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$proxysql\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$proxysql\"}[5m])) ",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_transmit_bytes_total{node_name=\"$proxysql\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{node_name=\"$proxysql\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$proxysql\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{node_name=\"$proxysql\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}