apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: sock-shop
  labels:
    app: elasticsearch
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: manual
# provisioner: kubernetes.io/no-provisioner
# #reclaimPolicy: Retain
# allowVolumeExpansion: true
# volumeBindingMode: Immediate #WaitForFirstConsumer    