export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
alias l="ls -ltrh"
alias c="clear"
alias h="cd ~"
alias v="cd /home/dk/Documents/virtual_machines"
alias g="cd /home/dk/Documents/git"
alias virdir="cd /home/dk/Documents/virtual_machines"
alias gitdir="cd /home/dk/Documents/git"
alias cls=clear
alias ltrh="ls -ltrh"
alias vs="vagrant global-status --prune"