apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    app: app1
spec:
  containers:
  - image: hellodk/svc1:v1
    name: app1
    imagePullPolicy: Always
    ports:
    - containerPort: 8086
      name: http
      protocol: TCP
