apiVersion: v1
kind: Pod
metadata:
  name: app2
  labels:
    app: app2
spec:
  containers:
  - image: hellodk/svc2:v1
    name: app2
    imagePullPolicy: Always
    ports:
    - containerPort: 8087
      name: http
      protocol: TCP
