worker_processes auto;

events { worker_connections 65535; }

http {
  geoip2 /usr/share/GeoIP/GeoLite2-City.mmdb {
    $geoip_country_code country iso_code;
    $geoip_city city names en;
    $geoip_lat location latitude;
    $geoip_lon location longitude;
  }

  log_format json escape=json
  '{'
    '"ts":"$time_iso8601",'
    '"status":$status,'
    '"rt":$request_time,'
    '"method":"$request_method",'
    '"path":"$uri",'
    '"country":"$geoip_country_code",'
    '"city":"$geoip_city",'
    '"lat":$geoip_lat,'
    '"lon":$geoip_lon'
  '}';

  access_log /var/log/nginx/access.log json;

  upstream backend { server backend:8080; }

  server {
    listen 80;
    location / { proxy_pass http://backend; }
  }
}
