apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    disk: ssd
spec:
  capacity: 
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mongodb
    fsType: ext4
