{
 "title": "Kubernetes cluster overview",
 "description": "This dashboard can help troubleshooting issue in Kubernetes cluster at cluster, node and namespace level.",
 "tags": [
  "kubernetes",
  "k8s",
  "namespace"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "label_values(up,cluster)" },
   {
    "name": "node",
    "query": "label_values(kube_node_created{cluster=\"$cluster\"},node)"
   },
   {
    "name": "namespace",
    "query": "query_result(kube_namespace_labels{cluster=\"$cluster\"})"
   },
   {
    "name": "container",
    "query": "kube_pod_container_info{cluster=\"$cluster\",namespace=\"$namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Overall cluster $cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$cluster cluster  node status",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "targets": [
    {
     "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$cluster cluster node status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\"}) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " count(count by (namespace)(kube_pod_info{cluster=\"$cluster\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": " count(count by (pod)(kube_pod_info{cluster=\"$cluster\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=\"$cluster\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{cluster=\"$cluster\",reason!=\"Completed\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting/Terminated pods",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_terminated_reason{cluster=\"$cluster\",reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{namespace}}"
    },
    {
     "expr": "count by(namespace,reason) (kube_pod_container_status_waiting_reason{cluster=\"$cluster\"} !=0 )",
     "legendFormat": "WAITING::{{reason}}::{{namespace}}"
    },
    {}
   ]
  },
  {
   "title": "PVCs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{cluster=\"$cluster\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReadOnly PVC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly{cluster=\"$cluster\"} != 0) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Besteffort  pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_qos_class{qos_class=\"BestEffort\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "burstable  pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_qos_class{qos_class=\"Burstable\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node  wise load in $cluster cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load5{cluster=\"$cluster\"} + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory usage in $cluster cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{cluster=\"$cluster\",pod!=\"POD\",namespace!=\"\"})",
     "legendFormat": "Total memory used in $cluster"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",resource=\"memory\"})",
     "legendFormat": "Total memory in $cluster"
    }
   ]
  },
  {
   "title": "Memory usage in $cluster cluster by node",
   "type": "graph",
   "description": "This panel shows node memory usage:\n\nnode_memory_MemTotal - node_memory_MemAvailable",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal{cluster=\"$cluster\"}  + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"}) - (node_memory_MemAvailable{cluster=\"$cluster\"}  + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"}))",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Memory usage by namespace in $cluster cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace)(container_memory_usage_bytes{cluster=\"$cluster\",pod!=\"POD\",namespace!=\"\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Overall CPU usage in $cluster cluster",
   "type": "graph",
   "description": "This panel shows node CPU utilisation",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (instance,nodename) (irate(node_cpu{cluster=\"$cluster\",mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"})",
     "legendFormat": "Total Used CPU in $cluster cluster"
    },
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster\",resource=\"cpu\"})",
     "legendFormat": "Total CPU in $cluster cluster"
    }
   ]
  },
  {
   "title": "Node CPU usage[5m] in $cluster cluster",
   "type": "graph",
   "description": "This panel shows node CPU utilisation",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance,nodename) (irate(node_cpu{cluster=\"$cluster\",mode!~\"guest.*|idle|iowait\"}[5m])) + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\"})",
     "legendFormat": "{{nodename}} "
    }
   ]
  },
  {
   "title": "$node Node details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": " (\n (sum(time() - node_boot_time{cluster=\"$cluster\"}+ on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"})) \nand \nON() kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\",node=\"$node\"} == 1 \n)"
      }
     ]
    },
    {
     "title": "Node $node Ready state ",
     "type": "graph",
     "description": "This panel shows the NotReady state of nodes. If any node goes in NotReady state, graph value will go from 1 to 0.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=\"Ready\",node=\"$node\"}) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Pod count on $node by namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (namespace)(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",node=\"$node\"})",
       "legendFormat": "{{namespace}}"
      },
      {}
     ]
    },
    {
     "title": "Memory/Disk/PID Pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kube_node_status_condition{cluster=\"$cluster\",status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure\",node=\"$node\"})",
       "legendFormat": "{{node}}::{{condition}}"
      }
     ]
    },
    {
     "title": "pod count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " count(count by (pod)(kube_pod_info{cluster=\"$cluster\",node=\"$node\",pod!=\"\"}))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "besteffort",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_pod_status_qos_class{qos_class=\"BestEffort\",node=\"$node\"})"
      }
     ]
    },
    {
     "title": "burstable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_pod_status_qos_class{qos_class=\"Burstable\",node=\"$node\"})"
      }
     ]
    },
    {
     "title": "Node $node load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load5{cluster=\"$cluster\"} + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"}",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity_cpu_cores{cluster=\"$cluster\",node=\"$node\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Node $node CPU usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(irate((sum by (instance) (node_cpu{cluster=\"$cluster\",mode!~\"guest.*|idle|iowait\"}))[5m:2m]) + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"})",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Total CPU requests on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\",node=\"$node\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Total CPU limits on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\",node=\"$node\"})",
       "legendFormat": "total limits"
      },
      {
       "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"cpu\"}",
       "legendFormat": "Total CPU"
      }
     ]
    },
    {
     "title": "Node $node memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal{cluster=\"$cluster\"}  + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"}) - (node_memory_MemAvailable{cluster=\"$cluster\"}  + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"})",
       "legendFormat": "{{nodename}}"
      },
      {
       "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "Total memory requests on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\",node=\"$node\"})",
       "legendFormat": "requests"
      },
      {
       "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "Total Memory limits on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (node)(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\",node=\"$node\"})",
       "legendFormat": "total liimits "
      },
      {
       "expr": "kube_node_status_capacity{cluster=\"$cluster\",node=\"$node\",resource=\"memory\"}",
       "legendFormat": "Total memory"
      }
     ]
    },
    {
     "title": "$node disk usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(sum by (instance,nodename,device) (node_filesystem_avail{cluster=\"$cluster\"} * on(instance) group_left(nodename) node_uname_info{cluster=\"$cluster\",nodename=\"$node\"}))",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Top 5  memory guzzling pods on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": " sort(topk(5, container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",node=\"$node\"}))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "kubelet_runtime_operations_errors_total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kubelet_runtime_operations_errors_total{job=\"kubelet\",cluster=\"$cluster\",node=\"$node\"}[5m])) by (node, operation_type)",
       "legendFormat": "{{node}}: {{operation_type}}"
      }
     ]
    },
    {
     "title": "kubelet_pleg_relist_duration_seconds_bucket",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (node,le) (rate(kubelet_pleg_relist_duration_seconds_bucket{cluster=\"$cluster\",node=\"$node\"}[5m])))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "NTP time deviation on $node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,nodename)(node_timex_estimated_error_seconds{cluster=\"$cluster\"}) + on(instance) group_left(nodename) \nnode_uname_info{cluster=\"$cluster\",nodename=\"$node\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "kubelet_eviction_stats_age_seconds_sum",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(kubelet_eviction_stats_age_seconds_sum{cluster=\"$cluster\",node=\"$node\"})",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  { "title": "Namespace $namespace details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Pod readiness in $namespace namespace",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "format": "none",
   "targets": [
    {
     "expr": "(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}::{{container}}"
    }
   ]
  },
  {
   "title": "Ready pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVCs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{cluster=\"$cluster\",namespace=\"$namespace\"}) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "pod count on nodes of $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (node)(kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "memory  usage by pods in $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": " sort(container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated{cluster=\"$cluster\",namespace=\"$namespace\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_deployment_created{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Readonly PVC",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly{cluster=\"$cluster\",namespace=\"$namespace\"} != 0) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "persistentvolumeclaim in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(kube_persistentvolumeclaim_access_mode{cluster=\"$cluster\",namespace=\"$namespace\"})",
     "legendFormat": "{{access_mode}}::{{persistentvolumeclaim}}"
    },
    {
     "expr": "kube_persistentvolumeclaim_status_phase{cluster=\"$cluster\",namespace=\"$namespace\",phase=\"Bound\"}",
     "legendFormat": "Bound::{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "pod restarts in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=\"$namespace\"}[2m]) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod  $container node relation",
   "type": "graph",
   "description": "This panel shows no. of pod restarts in a namespace. Please choose container name from top of dashboard to check for the nodes where the pod with same container has jumped.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_info{cluster=\"k8s\",namespace=\"$namespace\",pod=~\"$container.*\"})",
     "legendFormat": " {{node}}::  {{pod}}"
    }
   ]
  },
  {
   "title": "pod $container state in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_pod_container_status_ready{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"}) ",
     "legendFormat": "READY::{{pod}}::container $container"
    },
    {
     "expr": "(kube_pod_container_status_waiting{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "WAITING::{{pod}}::container $container "
    },
    {
     "expr": "(kube_pod_container_status_terminated{cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "TERMINATED::{{pod}}::container $container"
    }
   ]
  },
  {
   "title": " $namespace pods on $node",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "count by (pod)(container_memory_usage_bytes{cluster=\"$cluster\",namespace=\"$namespace\",node=\"$node\"})"
    }
   ]
  },
  {
   "title": "pods running in $namespace",
   "type": "table",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "kube_pod_info{cluster=\"$cluster\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Resource Quota in namespace $namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=\"$namespace\",resource=~\".*.memory.*\"}/1024^3",
     "legendFormat": "{{type}}::{{resource}} GB"
    },
    {
     "expr": "kube_resourcequota{cluster=\"$cluster\",namespace=\"$namespace\",resource=~\".*.storage.*\"}/1024^3",
     "legendFormat": "{{type}}::{{resource}} GB"
    }
   ]
  },
  {
   "title": "memory usage by container $container in $namespace namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " (container_memory_working_set_bytes{image!=\"\",cluster=\"$cluster\",namespace=\"$namespace\",container=\"$container\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}