{
 "title": "Kubernetes / Capacity Planning / Limits",
 "description": "Provides information relevant to fine-tuning container resource limits in Kubernetes",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_cpu_usage_seconds_total{name=~'.+', container!='POD', node=~\"$node\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_cpu_usage_seconds_total{name=~'.+', container!='POD', node=~\"$node\", namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_usage_seconds_total{name=~'.+', container!='POD', node=~\"$node\", namespace=~\"$namespace\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Available CPU",
   "type": "graph",
   "description": "Shows CPU used vs. allocatable CPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "Available cores ({{ instance }})"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "graph",
   "description": "Shows memory used vs. allocatable memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes) by (instance)/1024^3",
     "legendFormat": "Available memory ({{ instance }})"
    }
   ]
  },
  {
   "title": "CPU limits used",
   "type": "graph",
   "description": "CPU usage relative to the CPU limits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "% of limits" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod,container) (\n  irate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}[5m])\n)\n/\nsum by (namespace,pod,container) (\n  kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n) * 100",
     "legendFormat": "{{ namespace }}/{{ pod }}/{{ container }}"
    }
   ]
  },
  {
   "title": "Memory limits used",
   "type": "graph",
   "description": "Memory usage relative to the memory limits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "% of limits used" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,pod,container) (\n  container_memory_working_set_bytes{container!=\"POD\",container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n)\n/\nsum by (namespace,pod,container) (\n  kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}\n) * 100",
     "legendFormat": "{{ namespace }}/{{ pod }}/{{ container }}"
    }
   ]
  }
 ]
}