{
 "title": "kube-state-metrics-v2",
 "description": "Summary metrics about  kube-state-metrics v2 version(https://github.com/kubernetes/kube-state-metrics); Referenced 6417",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "2020-10-26T15:12:57.220Z", "to": "2020-10-26T17:22:15.978Z" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created{cluster=\"$cluster\"}, namespace)"
   },
   { "name": "datasource", "query": "Prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Pod Requested",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=~\"$node\",cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{node=~\"$node\",cluster=\"$cluster\",resource=\"pods\"})"
      }
     ]
    },
    {
     "title": "Cluster CPU Requested",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{node=~\"$node\",cluster=\"$cluster\",resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Cluster Memory  Requested",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable{node=~\"$node\",cluster=\"$cluster\",resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Cluster Pod Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "pods" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=\"$cluster\",resource=\"pods\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_pod_info{node=~\"$node\",cluster=\"$cluster\"})",
       "legendFormat": "requested"
      }
     ]
    },
    {
     "title": "Cluster CPU Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=\"$cluster\",resource=\"cpu\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=\"$cluster\",resource=\"cpu\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"})",
       "legendFormat": "limited"
      }
     ]
    },
    {
     "title": "Cluster Mem Capacity",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=\"$cluster\",resource=\"memory\"})",
       "legendFormat": "allocatable"
      },
      {
       "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=\"$cluster\",resource=\"memory\"})",
       "legendFormat": "capacity"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"})",
       "legendFormat": "limited"
      }
     ]
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "DiskOrMemoryPressure",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=~\"DiskPressure|MemoryPressure\", node=~\"$node\",cluster=\"$cluster\", status=\"true\"}==1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=\"$cluster\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\",cluster=\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=\"$cluster\"}",
       "legendFormat": "{{ statefulset}}"
      }
     ]
    },
    {
     "title": "Statefulset replicas",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=\"$cluster\"}/kube_statefulset_status_replicas{namespace=~\"$namespace\",cluster=\"$cluster\"}*100",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Pods restart in 30m",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=\"$cluster\"}[30m])>1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_reason{cluster=\"$cluster\",namespace=~\"$namespace\", reason=\"Evicted\"}==1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{cluster=\"$cluster\",namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=\"$cluster\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\" ,cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\",cluster=\"$cluster\"})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "kube_job_status_failed{namespace=~\"$namespace\",cluster=\"$cluster\"}>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\",cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\",cluster=\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "pvc is bound",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc is not bound",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}