# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

imports:
- path: cluster.jinja

resources:
- name: kubeflow
  type: cluster.jinja
  properties:
    zone: us-east1-d
    # Path for the bootstrapper image.
    bootstrapperImage: gcr.io/kubeflow-images-public/bootstrapper:latest
    bootstrapperConfig: |
      # For e2e test, we bake the kubeflow registry into the bootstrapperImage.
      # The bootstrapperImage field is modified during runtime to use 
      # the appropriate image name.
      app:
        packages:
          - name: core
            registry: kubeflow
          - name: tf-serving
            registry: kubeflow
          - name: tf-job
            registry: kubeflow
          - name: pytorch-job
            registry: kubeflow
        components:
          - name: kubeflow-core
            prototype: kubeflow-core
          - name: pytorch-operator
            prototype: pytorch-operator
        parameters:
          - component: kubeflow-core
            name: tfJobVersion
            value: v1alpha2
