{
 "title": "Kubernetes / Capacity Planning / Limits",
 "description": "Provides information relevant to fine-tuning container resource limits in Kubernetes",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "label_values(node)" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container_name!='POD', node=~\"$node\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container_name!='POD', node=~\"$node\", namespace=~\"$namespace\"}, pod_name)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(container_cpu_user_seconds_total{name=~'.+', container_name!='POD', node=~\"$node\", namespace=~\"$namespace\"}, container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Available CPU",
   "type": "graph",
   "description": "Shows CPU used vs. allocatable CPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{instance=~\"$node\", mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "Available cores ({{ instance }})"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "graph",
   "description": "Shows memory used vs. allocatable memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"$node\"}) by (instance)/1024^3",
     "legendFormat": "Available memory ({{ instance }})"
    }
   ]
  },
  {
   "title": "CPU limits used",
   "type": "graph",
   "description": "CPU usage relative to the CPU limits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "% of limits" }
   ],
   "targets": [
    {
     "expr": "sum (\n irate (\n container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\", node=~\"$node\", namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}[2m]\n )\n) by (namespace,pod_name,container_name)\n/\nsum (\n container_spec_cpu_quota{image!=\"\",container_name!=\"POD\", node=~\"$node\", namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}\n) by (namespace,pod_name,container_name)\n*\n10000000",
     "legendFormat": "{{ namespace }}/{{ pod_name }}/{{ container_name }}"
    }
   ]
  },
  {
   "title": "Memory limits used",
   "type": "graph",
   "description": "Memory usage relative to the memory limits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "% of limits used" }
   ],
   "targets": [
    {
     "expr": "(\n sum (\n container_memory_working_set_bytes{container_name!=\"POD\", node=~\"$node\", namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}\n ) by (namespace,pod_name,container_name)\n /\n sum (\n container_spec_memory_limit_bytes{container_name!=\"POD\",node=~\"$node\", namespace=~\"$namespace\", pod_name=~\"$pod\", container_name=~\"$container\"}\n ) by (namespace,pod_name,container_name)\n) * 100",
     "legendFormat": "{{ namespace }}/{{ pod_name }}/{{ container_name }}"
    }
   ]
  }
 ]
}