---
# Source: kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-operator
  namespace: monitoring
  labels:
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "74.0.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-74.0.0
    release: "monitoring"
    heritage: "Helm"
    app: monitoring-operator
    app.kubernetes.io/name: monitoring-prometheus-operator
    app.kubernetes.io/component: prometheus-operator
spec:
  
  endpoints:
  - port: https
    scheme: https
    tlsConfig:
      serverName: monitoring-operator
      ca:
        secret:
          name: monitoring-admission
          key: ca
          optional: false
    honorLabels: true
  selector:
    matchLabels:
      app: monitoring-operator
      release: "monitoring"
  namespaceSelector:
    matchNames:
      - "monitoring"
