---
# Source: kube-prometheus-stack/templates/alertmanager/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-alertmanager
  namespace: monitoring
  labels:
    app: monitoring-alertmanager
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "74.0.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-74.0.0
    release: "monitoring"
    heritage: "Helm"
spec:
  
  selector:
    matchLabels:
      app: monitoring-alertmanager
      release: "monitoring"
      self-monitor: "true"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: http-web
    enableHttp2: true
    path: "/metrics"
  - port: reloader-web
    path: "/metrics"
