---
# Source: kube-prometheus-stack/templates/prometheus/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-prometheus
  labels:
    app: monitoring-prometheus
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "74.0.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-74.0.0
    release: "monitoring"
    heritage: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-prometheus
subjects:
  - kind: ServiceAccount
    name: monitoring-prometheus
    namespace: monitoring
