
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring  
  labels:
    app: grafana
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grafana
  template:
    metadata:
      labels:
        component: grafana
    spec:
      volumes:
      - name: grafana-claim
        persistentVolumeClaim:
          claimName: grafana-claim
      containers:
      - name: grafana
        image: pharosproduction/grafana:6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3.6
        # Give `grafana` user (id 472) permissions a mounted volume
        # https://github.com/grafana/grafana-docker/blob/master/Dockerfile
        command:
        - chown
        - -R  
        - 472:472
        - /var/lib/grafana
        volumeMounts:
        - name: data
          mountPath: /var/lib/grafana
        # livenessProbe:
        #   exec:
        #     command:
        #       - wget 
        #       - localhost:3000
        #       - --spider
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   exec:
        #     command:
        #       - wget 
        #       - localhost:3000
        #       - --spider
          # initialDelaySeconds: 120
          # periodSeconds: 5
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-claim
 