---
# Source: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  release-name-monitoring-admission-create
  namespace: 1.33.1
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: monitoring-admission-create
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "74.0.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-74.0.0
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: monitoring-prometheus-operator
    app.kubernetes.io/component: prometheus-operator-webhook
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name:  release-name-monitoring-admission-create
      labels:
        app: monitoring-admission-create
        
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "74.0.0"
        app.kubernetes.io/part-of: monitoring
        chart: kube-prometheus-stack-74.0.0
        release: "release-name"
        heritage: "Helm"
        app.kubernetes.io/name: monitoring-prometheus-operator
        app.kubernetes.io/component: prometheus-operator-webhook
    spec:
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.4
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=release-name-monitoring-operator,release-name-monitoring-operator.1.33.1.svc
            - --namespace=1.33.1
            - --secret-name=release-name-monitoring-admission
          securityContext:
          
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: release-name-monitoring-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
---
# Source: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  release-name-monitoring-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: monitoring-admission-create
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "74.0.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-74.0.0
    release: "release-name"
    heritage: "Helm"
    app.kubernetes.io/name: monitoring-prometheus-operator
    app.kubernetes.io/component: prometheus-operator-webhook
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name:  release-name-monitoring-admission-create
      labels:
        app: monitoring-admission-create
        
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "74.0.0"
        app.kubernetes.io/part-of: monitoring
        chart: kube-prometheus-stack-74.0.0
        release: "release-name"
        heritage: "Helm"
        app.kubernetes.io/name: monitoring-prometheus-operator
        app.kubernetes.io/component: prometheus-operator-webhook
    spec:
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.4
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=release-name-monitoring-operator,release-name-monitoring-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=release-name-monitoring-admission
          securityContext:
          
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: release-name-monitoring-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
---
# Source: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  monitoring-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: monitoring-admission-create
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "74.0.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-74.0.0
    release: "monitoring"
    heritage: "Helm"
    app.kubernetes.io/name: monitoring-prometheus-operator
    app.kubernetes.io/component: prometheus-operator-webhook
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name:  monitoring-admission-create
      labels:
        app: monitoring-admission-create
        
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/version: "74.0.0"
        app.kubernetes.io/part-of: monitoring
        chart: kube-prometheus-stack-74.0.0
        release: "monitoring"
        heritage: "Helm"
        app.kubernetes.io/name: monitoring-prometheus-operator
        app.kubernetes.io/component: prometheus-operator-webhook
    spec:
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.4
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=monitoring-operator,monitoring-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=monitoring-admission
          securityContext:
          
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: monitoring-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
---
# Source: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  monitoring-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: monitoring-admission-create
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "74.0.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-74.0.0
    release: "monitoring"
    heritage: "Helm"
    app.kubernetes.io/name: monitoring-prometheus-operator
    app.kubernetes.io/component: prometheus-operator-webhook
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name:  monitoring-admission-create
      labels:
        app: monitoring-admission-create
        
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/version: "74.0.0"
        app.kubernetes.io/part-of: monitoring
        chart: kube-prometheus-stack-74.0.0
        release: "monitoring"
        heritage: "Helm"
        app.kubernetes.io/name: monitoring-prometheus-operator
        app.kubernetes.io/component: prometheus-operator-webhook
    spec:
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.4
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=monitoring-operator,monitoring-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=monitoring-admission
          securityContext:
          
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: monitoring-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
---
# Source: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  monitoring-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: monitoring-admission-create
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "74.0.0"
    app.kubernetes.io/part-of: monitoring
    chart: kube-prometheus-stack-74.0.0
    release: "monitoring"
    heritage: "Helm"
    app.kubernetes.io/name: monitoring-prometheus-operator
    app.kubernetes.io/component: prometheus-operator-webhook
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      name:  monitoring-admission-create
      labels:
        app: monitoring-admission-create
        
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/version: "74.0.0"
        app.kubernetes.io/part-of: monitoring
        chart: kube-prometheus-stack-74.0.0
        release: "monitoring"
        heritage: "Helm"
        app.kubernetes.io/name: monitoring-prometheus-operator
        app.kubernetes.io/component: prometheus-operator-webhook
    spec:
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.4
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=monitoring-operator,monitoring-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=monitoring-admission
          securityContext:
          
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            {}
      restartPolicy: OnFailure
      serviceAccountName: monitoring-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
