apiVersion: batch/v1
kind: Job
metadata:
  name: parallel
  labels:
    topic: jobs
spec:
  parallelism: 5
  completions: 10
  template:
    metadata:
      labels:
        topic: jobs
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        imagePullPolicy: Always
        args:
        - "--keygen-enable"
        - "--keygen-exit-on-complete"
        - "--keygen-num-to-gen=10"
      restartPolicy: OnFailure
