apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    cpu: "1000"
    memory: 200Gi
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
    pods: 10
