apiVersion: v1
kind: Pod
metadata:
  name: svc1
  labels:
    app: svc1-app
spec:
  containers:
  - image: hellodk/svc1:v1
    name: svc1
    imagePullPolicy: Always
    ports:
    - containerPort: 8086
      name: http
      protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: svc1-service
spec:
  selector:
    app: svc1-app
  ports:
    - port: 8086