apiVersion: v1
kind: Pod
metadata:
  name: svc2
  labels:
    app: svc2-app
spec:
  containers:
  - image: hellodk/svc2:v1
    name: svc2
    imagePullPolicy: Always
    ports:
    - containerPort: 8087
      name: http
      protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  name: svc2-service
spec:
  selector:
    app: svc2-app
  ports:
    - port: 8087