{
 "title": "HAproxy",
 "description": "HAproxy server, backend and frontend",
 "tags": [
  "haproxy",
  "backend",
  "frontend",
  "server"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,5m,15m,30m,1h,2h,1d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(haproxy_server_response_errors_total, exported_namespace)"
   },
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(haproxy_server_response_errors_total{exported_namespace=~\"$namespace\"}, route)"
   },
   { "name": "pod", "label": "Pod", "query": "label_values(haproxy_up, pod)" },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": "label_values(haproxy_frontend_connections_total{pod=~\"$pod\"}, frontend)"
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": "label_values(haproxy_backend_connections_total{pod=~\"$pod\"}, backend)"
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": "label_values(haproxy_frontend_http_responses_total{pod=~\"$pod\", frontend=~\"$frontend\"}, code)"
   }
  ]
 },
 "panels": [
  { "title": "Backend Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_http_responses_total{exported_namespace=~\"$namespace\", route=~\"$route\", pod=~\"$pod\", code=~\"$code\"}[$interval])",
     "legendFormat": "{{ code }} - {{ route }}"
    }
   ]
  },
  {
   "title": "Frontend HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_http_responses_total{namespace=~\"$namespace\", pod=~\"$pod\", code=~\"$code\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ code }} - {{ frontend }}"
    }
   ]
  },
  {
   "title": "Server Response Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_response_errors_total{exported_namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Frontend Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_bytes_in_total{namespace=~\"$namespace\", pod=~\"$pod\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Server Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_bytes_in_total{exported_namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Frontend Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_bytes_out_total{namespace=~\"$namespace\", pod=~\"$pod\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Server Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_bytes_out_total{exported_namespace=~\"$namespace\", route=~\"$route\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Server Connections Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_connections_total{exported_namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Frontend Connections Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_connections_total{namespace=~\"$namespace\", pod=~\"$pod\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Backend Connections Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_backend_connections_total{exported_namespace=~\"$namespace\",  route=~\"$route\", pod=~\"$pod\", backend=~\"$backend\"}[$interval])",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_connection_errors_total{exported_namespace=~\"$namespace\", route=~\"$route\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Backend Current Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_backend_current_queue{exported_namespace=~\"$namespace\", route=~\"$route\", pod=~\"$pod\", backend=~\"$backend\"}[$interval])",
     "legendFormat": "{{ backend }}, {{ exported_namespace }}"
    }
   ]
  },
  {
   "title": "Server Current Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_current_queue{exported_namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Frontend Max Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_max_sessions{namespace=~\"$namespace\", pod=~\"$pod\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Server Max Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_max_sessions{exported_namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Frontend Current Session",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_current_sessions{namespace=~\"$namespace\", pod=~\"$pod\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Server Current Session",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_current_sessions{exported_namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Frontend Current Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_current_session_rate{namespace=~\"$namespace\", pod=~\"$pod\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Server Current Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_current_session_rate{namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Frontend Max Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_max_sessions{namespace=~\"$namespace\", pod=~\"$pod\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Server Max Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_max_sessions{namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Frontend Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_frontend_max_session_rate{namespace=~\"$namespace\", pod=~\"$pod\", frontend=~\"$frontend\"}[$interval])",
     "legendFormat": "{{ frontend }}"
    }
   ]
  },
  {
   "title": "Server Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(haproxy_server_max_session_rate{namespace=~\"$namespace\", pod=~\"$pod\", route=~\"$route\"}[$interval])",
     "legendFormat": "{{ route }}"
    }
   ]
  }
 ]
}