{
 "title": "Kubernetes Node Monitoring",
 "description": "https://em8g.com - free kubernetes monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"agent.hostname\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Visualization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "description": "The percentage of CPU time in states other than Idle and IOWait, normalised by the number of cores.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.cpu.total.norm.pct", "id": "1", "type": "avg" }
     ],
     "query": "agent.hostname:$node AND event.dataset:system.cpu",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "description": "The percentage of used memory.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.memory.actual.used.pct", "id": "1", "type": "avg" }
     ],
     "query": "agent.hostname:$node AND event.dataset:system.memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filesystem Usage %",
   "type": "graph",
   "description": "Filesystem total used in bytes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.used.bytes",
       "hide": true,
       "id": "1",
       "type": "sum"
      },
      {
       "field": "kubernetes.node.fs.capacity.bytes",
       "hide": true,
       "id": "4",
       "type": "sum"
      },
      {
       "id": "5",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "1" },
        { "name": "var2", "pipelineAgg": "4" }
       ],
       "settings": { "script": "params.var1 / params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network In (rx)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.network.rx.bytes",
       "hide": true,
       "id": "1",
       "settings": {
        "script": "_value  / $__interval_ms * 1000"
       },
       "type": "sum"
      },
      { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Out (tx)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.network.tx.bytes",
       "hide": true,
       "id": "1",
       "settings": {
        "script": "_value  / $__interval_ms * 1000"
       },
       "type": "sum"
      },
      { "field": "1", "id": "4", "pipelineAgg": "1", "type": "derivative" }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Swap Memory Usage",
   "type": "graph",
   "description": "Used swap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent.hostname",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system.memory.swap.used.bytes", "id": "1", "type": "avg" }
     ],
     "query": "agent.hostname:$node AND event.dataset:system.memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Monitoring",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "agent.hostname:$node AND event.dataset:kubernetes.node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}