apiVersion: v1
kind: Service
metadata:
  name: liveness
  labels:
    app: liveness
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: liveness
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: liveness
spec:
  template:
    metadata:
      labels:
        app: liveness
    spec:
      containers:
      - name: liveness
        image: k8s.gcr.io/busybox
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 3600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
